#!/usr/bin/env python3
"""
================================================================================
 summarize.py — cross-dataset benchmark summary for the EEG-MI pipeline
================================================================================
Reads results_master.csv (mean acc/f1 per dataset|channels|model) and
folds_master.json (per-fold acc, for significance) written by eeg_engine.py,
and writes summary_report.md with:
  1. a pivot table (rows = dataset x channels config, cols = model, cell =
     acc_mean), best model per row marked *, models not significantly
     different from it (Holm-Bonferroni-corrected paired Wilcoxon across
     folds) marked ~ — same convention as eeg_engine.py's console table.
  2. a "why" table: one row per dataset with its montage/coverage and a short
     rationale, to make explicit the pattern noted in CLAUDE.md — accuracy
     tracks motor-cortex coverage, not raw channel count.

Deps: pandas, numpy, scipy (already required by the rest of the pipeline).
================================================================================
"""
import json, os, sys
import numpy as np
import pandas as pd
from significance import pairwise_significance

RESULTS_CSV = "results_master.csv"
FOLDS_JSON = "folds_master.json"
OUT_MD = "summary_report.md"

# Short, hand-maintained rationale per dataset — the "why" behind the numbers.
# Add an entry here whenever a new dataset is benchmarked.
DATASET_INFO = {
    "eeg_dataset_emotiv.csv": {
        "montage": "Emotiv EPOC X, 14ch (no C3/C4)",
        "why": "No true motor electrodes; premotor proxy (F3/F4/FC5/FC6) exists but trimming to it "
               "LOWERS accuracy — a hardware-coverage limitation, not a preprocessing bug.",
    },
    "BCI-IV-2b": {
        "montage": "3-channel C3/Cz/C4 (dedicated motor montage)",
        "why": "Direct motor-cortex coverage on every channel — highest LOPO ceiling of the three "
               "datasets despite having by far the fewest channels.",
    },
    "PhysioNet-MI (left_hand/right_hand)": {
        "montage": "64-channel 10-20, full scalp (research montage)",
        "why": "Motor coverage is present but diluted among 64 channels, and 109 heterogeneous "
               "subjects add the largest inter-subject variance of the three datasets.",
    },
}

def load_folds():
    if not os.path.exists(FOLDS_JSON):
        sys.exit(f"{FOLDS_JSON} not found — run eeg_engine.py at least once first.")
    return json.load(open(FOLDS_JSON))

def build_pivot(df, folds):
    """-> markdown table string: rows=(dataset,channels), cols=model, cells=acc_mean w/ */~ marks."""
    models = sorted(df["model"].unique(), key=lambda m: (m != "Shrinkage-LDA", m))
    rows = []
    for (dataset, channels), g in df.groupby(["dataset", "channels"], sort=False):
        key = f"{dataset}|{channels}"
        sig = None
        if key in folds:
            model_accs = {m: d["acc"] for m, d in folds[key]["models"].items()}
            if len(model_accs) > 1:
                sig = pairwise_significance(model_accs)
        row = {"dataset": dataset, "channels": channels}
        for m in models:
            sub = g[g["model"] == m]
            if sub.empty:
                row[m] = ""
                continue
            acc = float(sub["acc_mean"].iloc[0])
            mark = ""
            if sig and m in sig:
                mark = " *" if sig[m]["is_best"] else (" ~" if sig[m]["tied_with_best"] else "")
            row[m] = f"{acc:.3f}{mark}"
        rows.append(row)
    piv = pd.DataFrame(rows)
    return piv, models

def markdown_table(df):
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |",
             "|" + "|".join(["---"] * len(cols)) + "|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    return "\n".join(lines)

def build_why_table(df):
    rows = []
    for dataset, g in df.groupby("dataset", sort=False):
        best = g.loc[g["acc_mean"].astype(float).idxmax()]
        info = DATASET_INFO.get(dataset, {"montage": "(undocumented — add to DATASET_INFO)",
                                           "why": "(undocumented — add to DATASET_INFO)"})
        rows.append({"dataset": dataset, "montage": info["montage"],
                     "best_config": f"{best['channels']} / {best['model']}",
                     "best_acc": f"{float(best['acc_mean']):.3f}",
                     "why": info["why"]})
    return pd.DataFrame(rows)

def main():
    if not os.path.exists(RESULTS_CSV):
        sys.exit(f"{RESULTS_CSV} not found — run eeg_engine.py at least once first.")
    df = pd.read_csv(RESULTS_CSV)
    folds = load_folds()

    piv, models = build_pivot(df, folds)
    why = build_why_table(df)

    out = []
    out.append("# Cross-dataset benchmark summary\n")
    out.append("Auto-generated by `summarize.py` from `results_master.csv` + `folds_master.json`. "
                "Do not hand-edit — re-run `summarize.py` instead.\n")
    out.append("## Accuracy pivot (mean, LOPO cross-subject)\n")
    out.append("`*` best mean accuracy in that row · `~` not significantly different from best "
                "(paired Wilcoxon across folds, Holm-Bonferroni corrected, alpha=0.05). "
                "Blank = model not run for that config.\n")
    out.append(markdown_table(piv) + "\n")
    out.append("## Why the numbers differ across datasets\n")
    out.append(markdown_table(why) + "\n")
    text = "\n".join(out)
    with open(OUT_MD, "w") as f:
        f.write(text)
    print(f"wrote {OUT_MD}  ({len(piv)} dataset/channel rows, {len(models)} models, "
          f"{len(why)} datasets in the why-table)")

if __name__ == "__main__":
    main()
